fastlane_version "1.51.0"

default_platform :ios

platform :ios do

  before_all do
    cocoapods
  end

  desc "Run all tests"
  lane :unittests do
    scan(scheme: "ELColorGame", device: "iPhone 6s (9.2)")
  end

  desc "Create a new Beta Build and upload to Apple TestFlight"
  lane :testflight do
    gym
    pilot(skip_submission: true)
  end

end

